{
 "title": "Presioa azkeneko orduan.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Presioa denbora errealean.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-5s , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"pres\")\n |> group(columns: [])\n |> mean()\n "
    }
   ]
  },
  {
   "title": "Batazbesteko presioa azkeneko orduan.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-1h , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"pres\")\n |> group(columns:[])\n |>mean()"
    }
   ]
  },
  {
   "title": "Presio maximoa azkenko orduan.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-1h , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"pres\")\n |> group(columns: [\"_time\"])\n |> aggregateWindow(every: 10s, fn: mean)\n |> group(columns: [\"_time\"])\n |> mean()  \n |> keep(columns: [\"_value\"])\n |> max()\n\n\n"
    }
   ]
  },
  {
   "title": "Presioa Azkeneko orduan.",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-1h , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"pres\")\n |> aggregateWindow(every: 10s, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}