{
 "title": "Temperatura azkeneko orduan.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura denbora errealean",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-10s , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n |> group(columns: [])\n |> mean()\n "
    }
   ]
  },
  {
   "title": "Batazbesteko temperatura azkeneko orduan.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-1h, stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n |> group(columns:[\"time\"])\n |> mean()"
    }
   ]
  },
  {
   "title": "Batazbesteko maximoa azkenko orduan.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-1h , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n |> aggregateWindow(every: 10s, fn: mean)\n |> group(columns: [\"_time\"])\n |> mean()  \n |> max(column: \"_value\")\n |> keep(columns: [\"_value\"])\n\n"
    }
   ]
  },
  {
   "title": "Temperatura Azkeneko orduan.",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-1h , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n |> aggregateWindow(every: 5s, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}