{
 "title": "Tenperatura azkeneko 24 ordutan.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tenperatura denbora errealean",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-5s , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n |> group(columns: [])\n |> mean()\n "
    }
   ]
  },
  {
   "title": "Batazbesteko tenperatura azkeneko 24 ordutan.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-24h, stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n |> aggregateWindow(every: 30s, fn: mean)\n |> group(columns:[])\n |> mean()"
    }
   ]
  },
  {
   "title": "Batazbesteko maximoa azkenko 24 ordutan.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-24h , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n |> aggregateWindow(every: 1m, fn: mean)\n |> group(columns: [\"_time\"])\n |> mean()  \n |> max(column: \"_value\")\n |> keep(columns: [\"_value\"])\n\n"
    }
   ]
  },
  {
   "title": "Tenperatura Azkeneko 24 ordutan.",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ehu\")\n |> range(start:-24h , stop:now())\n |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n |> aggregateWindow(every: 1m, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}